// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PollMe.DataAccess;

namespace PollMe.DataAccess.Migrations
{
    [DbContext(typeof(PollMeContext))]
    [Migration("20200329000325_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PollMe.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EncuestaId");

                    b.Property<string>("Respuesta");

                    b.Property<int>("Votos");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("PollMe.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaEvento");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("PollMe.Domain.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreadoEn");

                    b.Property<int>("EventoId");

                    b.Property<string>("Pregunta");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("PollMe.Domain.Entities.Answer", b =>
                {
                    b.HasOne("PollMe.Domain.Poll", "Encuesta")
                        .WithMany("Respuestas")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PollMe.Domain.Poll", b =>
                {
                    b.HasOne("PollMe.Domain.Entities.Event", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
